openapi: 3.0.0
info:
  title: Chat Messenger API
  version: 1.0.0
paths:
  /chat/messages:
    get:
      summary: Get all messages
      responses:
        '200':
          description: A list of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
                    user:
                      type: string
                    timestamp:
                      type: string
        '401':
          description: Unauthorized, invalid or missing token
  /chat/message/send:
    post:
      summary: Send a new message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                user:
                  type: string
      responses:
        '204':
          description: Message sent successfully
        '400':
          description: Bad request, invalid input
        '401':
          description: Unauthorized, invalid or missing token
  /auth/login:
    post:
      summary: Log in a user and get a JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Bad request, invalid input
        '401':
          description: Unauthorized, invalid username or password
